#!/bin/sh

# default flags
alias \
  cp='cp -ivr' \
  mv='mv -iv' \
  rm='rm -v' \
  df='df -h' \
  bc='bc -ql' \
  ls='ls -h --color=auto' \
  ll='ls -lh --color=auto' \
  la='ls -lha --color=auto' \
  rg='rg -i' \
  mkd='mkdir -pv' \

# abbreviate
alias \
  v='nvim' \
  j='julia --quiet' \
  n='node' \
  py='python' \
  sv='sudo nvim' \
  sdn='shutdown now' \
  ka='killall' \
  dc='docker-compose'

# abstract
alias \
  dots='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' \
  vf='nvim -o `fzf`' \
  h='history | fzf' \
  bubu='brew update && brew upgrade' \

# colorize
alias \
  diff='colordiff' \
  ccat="highlight --out-format=ansi" \
  grep='grep --color=auto' \

# cd
alias \
  ..='cd ..' \
  ...='cd ../..' \
  .3='cd ../../..' \
  .4='cd ../../../..' \
  .5='cd ../../../../..' \

# git
alias \
  g='git' \
  ga='git add' \
  gb='git branch' \
  gc='git commit' \
  gd='git diff' \
  gl='git log' \
  gp='git push' \
  gr='git restore' \
  gpl='git pull' \
  gst='git status' \
  gca='git commit -v --amend' \
  gco='git checkout' \
  gdc='git diff --cached' \
  glo='git log --oneline' \
  glg='git log --oneline --decorate --graph --all' \

# npm
alias \
  nr='npm run' \
  nrs='npm run start' \
