#!/bin/sh

# default flags
alias \
  cp='cp -ivr' \
  mv='mv -iv' \
  rm='rm -Iv' \
  df='df -h' \
  bc='bc -ql' \
  mkd='mkdir -pv' \
  free='free -wh' \

# abbreviate
alias \
  p='sudo pacman' \
  v='nvim' \
  j='julia --quiet' \
  n='node' \
  py='python' \
  dc='docker container' \
  sv='sudo nvim' \
  sw='termdown' \
  sdn='shutdown now' \
  ka='killall' \
  cs='xclip -selection clipboard' \
  vs='xclip -o -selection clipboard' \
  cpwd='pwd | xclip -selection clipboard' \

# abstract
alias \
  dropcaches='sudo paccache -rk3; yay -Sc --aur --noconfirm' \
  droporphans='sudo pacman -Qtdq | sudo pacman -Rns -' \
  dropall='dropcaches && dropcaches' \
  dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' \
  nf='nvim -o `fzf`' \
  h='history | fzf' \

# colorize
alias \
  ls='ls -hN --color=auto --group-directories-first' \
  ll='ls -lh --color=auto' \
  la='ls -lha --color=auto' \
  diff='colordiff' \
  ccat="highlight --out-format=ansi" \
  grep='grep --color=auto' \

# cd
alias \
  ..='cd ..' \
  ...='cd ../..' \
  .3='cd ../../..' \
  .4='cd ../../../..' \
  .5='cd ../../../../..' \

# git
alias \
  g='git' \
  ga='git add' \
  gb='git branch' \
  gc='git commit' \
  gd='git diff' \
  gl='git log' \
  gp='git push' \
  gs='git switch' \
  gr='git restore' \
  gpl='git pull' \
  gsc='git switch -c' \
  gst='git status' \
  gca='git commit -v --amend' \
  gcb='git checkout -b' \
  gco='git checkout' \
  gdc='git diff --cached' \
  glo='git log --oneline' \
  glg='git log --oneline --decorate --graph --all' \

# npm
alias \
  nr='npm run' \
  nrs='npm run start' \
